version: "3"
services: 
  db:
    image: postgres:latest
    container_name: psql-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
  
  # adminer:
  #   image: adminer:latest
  #   restart: always
  #   ports:
  #     - 8091:8080

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4
  #   restart: always
  #   ports:
  #     - "8888:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  # pgadmin-data:
