services: 
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: 
      - 5432:5432
  
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8091:8080

volumes:
  pgdata:
